### ISSUE TITLE
Chinese talk game shows garbled

### ISSUE THREAD

**Issue by 460450180** [StygianTheBest/AzerothCore-Content#2]
Hello, I like the way you write very much, maybe I don't call it professional, I have downloaded and added some scripts to my server, such as CODEBOX_NPC, Congratsonlevel, GAMBLE_NPC, Startguild, but there is a problem that changes NPC The talk content code into Chinese game after the show garbled, I am a novice, how should I do? Sorry, translation from Bing.

**Comment by 460450180** [comment]
I'm looking forward to your letter.

**Comment by StygianTheBest** [comment]
I've never seen this issue. Do you have any screenshots so I can get an idea of what you're seeing?
