### ISSUE TITLE
The AzerothCorePersonalTeleporter.sql not working

### ISSUE THREAD

**Issue by ppishero** [StygianTheBest/AzerothCore-Content#5]
I used this sql, but the NPC dialog created is blank.

what should I do？
![image](https://user-images.githubusercontent.com/8230378/44308899-a6294080-a3f0-11e8-940a-c701e526d2a0.png)

**Comment by ppishero** [comment]
you miss sql, i got the right sql

**Comment by Hangasilly** [comment]
Hey, same issue for me:

Put in the SQL into thoses tables, but there's no gossip or else:
![img_017](https://user-images.githubusercontent.com/40966167/107952322-e81fa700-6f99-11eb-80ae-8c2a6bd4b15a.jpg)
