### ISSUE TITLE
AzerothCoremall.sql 

### ISSUE THREAD

**Issue by ELdoBA** [StygianTheBest/AzerothCore-Content#6]
Hi @StygianTheBest. There is a problem in your sql file. Actually if you talk with Weapon Master Vendor, as any class even if you are not DK, he will teach you some Death Knight abilities..  
Will be great if you can edit it, since Mall and Vendors are awesome. Greetings
![hunt](https://user-images.githubusercontent.com/41213210/46145527-af63c380-c260-11e8-846a-172143ed5343.png)
![hunt1](https://user-images.githubusercontent.com/41213210/46145528-af63c380-c260-11e8-9cb7-0f2ef61d41fb.png)
![hunt2](https://user-images.githubusercontent.com/41213210/46145529-af63c380-c260-11e8-9734-31b3507fb403.png)

```
-- Weapon Master
SET
@Entry             := @Entry + 1,
@Name             := "Weapon Master",
@TrainerClass    := 1,
@Title             := "Global Trainer";
INSERT INTO creature_template (entry, modelid1, name, subname, IconName, gossip_menu_id, minlevel, maxlevel, faction, npcflag, speed_walk, speed_run, scale, rank, unit_class, unit_flags, unit_flags2, type, type_flags, trainer_type, trainer_spell, trainer_class, trainer_race, InhabitType, RegenHealth, flags_extra, AiName, ScriptName, VerifiedBuild)
VALUES
(@Entry, @Model, @Name, @Title, @Icon, @GossipMenu, @MinLevel, @MaxLevel, @Faction, @NPCFlag, 1, 1.14286, @Scale, @Rank, 1, @UnitFlags, @UnitFlags2, @Type, @TypeFlags, @TrainerType, @TrainerSpell, @TrainerClass, @TrainerRace, 3, 1, @FlagsExtra, @AIName, @Script, @VerifiedBuild);
```

**Comment by StygianTheBest** [comment]
Thanks for the comment. I am aware of this issue. It's been a while, so I can't remember exactly what the problem is but it's most likely a wrong flag set somewhere. There's not much involved in creating these vendors, so anyone willing to play around and test it should be able to fix it. I'm limited on time for AC these days, but if I fix it or anyone else does I'll update it.

**Comment by StygianTheBest** [comment]
This has been corrected in the StygianCore Repack by adding a World Trainer who handles everything for all classes.
